services:
  frontend:
    container_name: tl-frontend
    restart: always
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 3000:3000

  backend:
    container_name: tl-backend
    restart: always
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    env_file:
      - ./backend/.env.docker
    ports:
      - 2000:2000
  
  database:
    container_name: tl-database
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Admin1234"
    ports:
      - 3306:3306
    volumes:
      - database-data:/data/db

volumes:
  database-data: